const hospitalData = {
  "Phoenix Children's Hosptial": {
    Image: "/assets/phoenix-hospital.jpg",
    "Annual Visits": "320,000",
    "Phone Number": "(602) 933-1000",
    Description:
      "A top-rated hospital excelling in respiratory, cardiac, and infectious diseases, with a focus on treating younger children. Known for its advanced equipment and specialized care.",
    Address: "1919 E Thomas Rd, Phoenix, AZ",
    Stars: "4.6",
    Equipment: [
      "Ventilator",
      "Defibrillator",
      "Pulse oximeter",
      "IV pump",
      "Blood pressure cuff",
      "Laryngoscope",
      "Endotracheal tubes",
      "Crash cart",
      "CT scanner",
      "Nebulizer",
      "Infant warmer",
    ],
    "Pediatric Coordinator": "Yes",
    "Pediatric Doctors": {
      "Dr. Susan Matthews": [
        "Graduated from Stanford University School of Medicine (2001)",
        "PhD in Pediatric Pulmonology",
        "22 years of experience",
      ],
      "Dr. Ryan Chen": [
        "Graduated from Harvard Medical School (1998)",
        "Fellowship in Pediatric Cardiology",
        "25 years of experience",
      ],
    },
    "Disease Categories": [
      "Respiratory",
      "Cardiac",
      "Infectious Diseases",
      "Neurological",
      "Skeletal",
      "Chronic Conditions",
      "Gastrointestinal",
    ],
    "Average Patient Age": 6,
  },
  "Banner Thunderbird Medical Center": {
    Image: "/assets/banner-hospital.jpg",
    "Annual Visits": "150,000",
    "Phone Number": "(602) 865-5555",
    Description:
      "Specializes in neurological emergencies like seizures and skeletal issues such as fractures. Ideal for school-aged children needing immediate care.",
    Address: "5555 W Thunderbird Rd, Glendale, AZ",
    Stars: "4.3",
    Equipment: [
      "Ventilator",
      "Pulse oximeter",
      "Blood pressure cuff",
      "Crash cart",
      "Glucometer",
      "Nebulizer",
      "Suction device",
    ],
    "Pediatric Coordinator": "No",
    "Pediatric Doctors": {
      "Dr. Kimberly Sanders": [
        "Graduated from the University of Arizona College of Medicine (2005)",
        "Board-certified in Pediatric Emergency Medicine",
        "18 years of experience",
      ],
      "Dr. Miguel Torres": [
        "Graduated from UCLA David Geffen School of Medicine (2007)",
        "Fellowship in Pediatric Neurology",
        "16 years of experience",
      ],
    },
    "Disease Categories": [
      "Neurological",
      "Skeletal",
      "Gastrointestinal",
      "Respiratory",
      "Infectious Diseases",
      "Cardiac",
      "Chronic Conditions",
    ],
    "Average Patient Age": 13,
  },
  "Nicklaus Children's Hospital": {
    Image: "/assets/Nicklaus.png",
    "Annual Visits": "280,000",
    "Phone Number": "(305) 666-6511",
    Description:
      "Renowned for gastrointestinal treatments (e.g., appendicitis) and orthopedic care for fractures. Offers comprehensive care for middle-aged pediatric patients.",
    Address: "3100 SW 62nd Ave, Miami, FL",
    Stars: "4.7",
    Equipment: [
      "Ventilator",
      "Defibrillator",
      "Pulse oximeter",
      "IV pump",
      "Blood pressure cuff",
      "Laryngoscope",
      "Endotracheal tubes",
      "Crash cart",
      "CT scanner",
      "Glucometer",
      "Infant warmer",
    ],
    "Pediatric Coordinator": "No",
    "Pediatric Doctors": {
      "Dr. Andrea Rivera": [
        "Graduated from Johns Hopkins School of Medicine (2004)",
        "Specialization in Pediatric Orthopedics",
        "19 years of experience",
      ],
      "Dr. Sophia Patel": [
        "Graduated from Emory University School of Medicine (2002)",
        "Fellowship in Pediatric Gastroenterology",
        "21 years of experience",
      ],
    },
    "Disease Categories": [
      "Gastrointestinal",
      "Skeletal",
      "Chronic Conditions",
      "Infectious Diseases",
      "Neurological",
      "Respiratory",
      "Cardiac",
    ],
    "Average Patient Age": 8,
  },
  "Holtz Children's Hospital at UM/Jackson Memorial": {
    Image: "/assets/holtz-hospital.jpg",
    "Annual Visits": "200,000",
    "Phone Number": "(305) 585-5437",
    Description:
      "Excels in trauma, respiratory conditions, and chronic disorders, providing specialized care for older children and teens.",
    Address: "1611 NW 12th Ave, Miami, FL",
    Stars: "4.4",
    Equipment: [
      "Ventilator",
      "Defibrillator",
      "Pulse oximeter",
      "Blood pressure cuff",
      "Crash cart",
      "Nebulizer",
      "Telemedicine system",
    ],
    "Pediatric Coordinator": "Yes",
    "Pediatric Doctors": {
      "Dr. Benjamin Scott": [
        "Graduated from University of Miami Miller School of Medicine (2003)",
        "Specialization in Pediatric Trauma Surgery",
        "20 years of experience",
      ],
      "Dr. Leila Vasquez": [
        "Graduated from Columbia University Vagelos College of Physicians and Surgeons (2000)",
        "Fellowship in Pediatric Endocrinology",
        "23 years of experience",
      ],
    },
    "Disease Categories": [
      "Respiratory",
      "Neurological",
      "Skeletal",
      "Chronic Conditions",
      "Infectious Diseases",
      "Gastrointestinal",
      "Cardiac",
    ],
    "Average Patient Age": 10,
  },
  "Texas Children's Hospital": {
    Image: "/assets/texas-hospital.png",
    "Annual Visits": "400,000",
    "Phone Number": "(832) 824-1000",
    Description:
      "A leader in cardiac and respiratory care, handling complex congenital heart issues and asthma. Highly experienced in treating young children.",
    Address: "6621 Fannin St, Houston, TX",
    Stars: "4.8",
    Equipment: [
      "Ventilator",
      "Defibrillator",
      "Pulse oximeter",
      "IV pump",
      "Blood pressure cuff",
      "Laryngoscope",
      "Endotracheal tubes",
      "Crash cart",
      "CT scanner",
      "Glucometer",
      "Nebulizer",
      "Telemedicine system",
      "Infant warmer",
    ],
    "Pediatric Coordinator": "Yes",
    "Pediatric Doctors": {
      "Dr. Olivia Park": [
        "Graduated from Yale School of Medicine (1999)",
        "Fellowship in Pediatric Cardiology",
        "25 years of experience",
      ],
      "Dr. Ethan Ramirez": [
        "Graduated from Baylor College of Medicine (2002)",
        "Specialization in Pediatric Neurology",
        "23 years of experience",
      ],
    },
    "Disease Categories": [
      "Cardiac",
      "Respiratory",
      "Neurological",
      "Gastrointestinal",
      "Infectious Diseases",
      "Skeletal",
      "Chronic Conditions",
    ],
    "Average Patient Age": 1,
  },
  "Houston Methodist Children's Hospital": {
    Image: "/assets/houston-hospital.png",
    "Annual Visits": "120,000",
    "Phone Number": "(713) 441-5451",
    Description:
      "Known for its expertise in infectious diseases and skeletal conditions, providing top-notch care for school-aged children with fractures or flu.",
    Address: "6565 Fannin St, Houston, TX",
    Stars: "4.5",
    Equipment: [
      "Defibrillator",
      "Pulse oximeter",
      "IV pump",
      "Blood pressure cuff",
      "Crash cart",
      "Nebulizer",
      "CT scanner",
      "Infant warmer",
      "Glucometer",
      "Suction device",
    ],
    "Pediatric Coordinator": "Yes",
    "Pediatric Doctors": {
      "Dr. Grace Thompson": [
        "Graduated from Duke University School of Medicine (2000)",
        "Specialization in Pediatric Infectious Diseases",
        "24 years of experience",
      ],
      "Dr. Ryan Chen": [
        "Graduated from University of Texas Southwestern Medical School (2005)",
        "Fellowship in Pediatric Orthopedics",
        "19 years of experience",
      ],
    },
    "Disease Categories": [
      "Infectious Diseases",
      "Skeletal",
      "Respiratory",
      "Chronic Conditions",
      "Neurological",
      "Cardiac",
      "Gastrointestinal",
    ],
    "Average Patient Age": 6,
  },
  "Joe DiMaggio Children's Hospital": {
    Image: "/assets/joe-hospital.png",
    "Annual Visits": "180,000",
    "Phone Number": "(954) 265-5324",
    Description:
      "Focused on respiratory and neurological care, such as asthma and concussions. A reliable choice for children ages 8 to 11.",
    Address: "3501 Johnson Street, Hollywood, FL 33021",
    Stars: "4.6",
    Equipment: [
      "Ventilator",
      "Defibrillator",
      "Pulse oximeter",
      "Blood pressure cuff",
      "Crash cart",
      "CT scanner",
      "Glucometer",
      "Nebulizer",
      "Suction device",
    ],
    "Pediatric Coordinator": "Yes",
    "Pediatric Doctors": {
      "Dr. Isabella Lopez": [
        "Graduated from University of Miami Miller School of Medicine (2006)",
        "Specialization in Pediatric Pulmonology",
        "18 years of experience",
      ],
      "Dr. Ryan Chen": [
        "Graduated from Boston University School of Medicine (2003)",
        "Fellowship in Pediatric Emergency Medicine",
        "21 years of experience",
      ],
    },
    "Disease Categories": [
      "Respiratory",
      "Neurological",
      "Skeletal",
      "Infectious Diseases",
      "Chronic Conditions",
      "Cardiac",
      "Gastrointestinal",
    ],
    "Average Patient Age": 8,
  },
  "Texas Children's Hospital West Campus": {
    Image: "/assets/texas-west-hospital.png",
    "Annual Visits": "140,000",
    "Phone Number": "(832) 227-1000",
    Description:
      "Specializes in gastrointestinal and respiratory treatments, such as appendicitis and asthma. Well-suited for younger children and preteens.",
    Address: "18200 Katy Fwy, Houston, TX",
    Stars: "4.4",
    Equipment: [
      "Ventilator",
      "Defibrillator",
      "Pulse oximeter",
      "IV pump",
      "Blood pressure cuff",
      "Crash cart",
      "CT scanner",
      "Glucometer",
      "Infant warmer",
      "Suction device",
    ],
    "Pediatric Coordinator": "No",
    "Pediatric Doctors": {
      "Dr. Emily Carter": [
        "Graduated from Johns Hopkins School of Medicine (2002)",
        "Specialization in Pediatric Gastroenterology",
        "22 years of experience",
      ],
      "Dr. Lucas King": [
        "Graduated from University of Chicago Pritzker School of Medicine (2004)  ",
        "Fellowship in Pediatric Emergency Medicine",
        "20 years of experience",
      ],
    },
    "Disease Categories": [
      "Gastrointestinal",
      "Respiratory",
      "Infectious Diseases",
      "Chronic Conditions",
      "Neurological",
      "Chronic Conditions",
      "Cardiac",
    ],
    "Average Patient Age": 6,
  },
};
